apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
  labels:
    app.kubernetes.io/instance: ollama
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.30.11
  share: /nfsshare
  subDir: "ollama/${pvc.metadata.namespace}/${pvc.metadata.name}"
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.1
